### ISSUE TITLE
update setup guide

### ISSUE THREAD

**Issue by idnovic** [k00n/usbguard-gnome#14]
Your current setup guide leaves the user with leftovers.
Maybe use mv instead of cp. 

Also you removed the folder creation of the guide but are still using the following command:
`git clone https://github.com/6E006B/usbguard-gnome.git .`
The . at the end means write in the current working directory. But you removed the folder creation. This is now unclean. Remove the dot.

Problem:
```
[idnovic@id-lappy ~]0$ mkdir /tmp/tester
[idnovic@id-lappy ~]0$ cd /tmp/tester/
[idnovic@id-lappy /tmp/tester]0$ git clone https://github.com/6E006B/usbguard-gnome.git .
Klone nach '.' ...
remote: Enumerating objects: 56, done.
remote: Counting objects: 100% (56/56), done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 338 (delta 32), reused 47 (delta 26), pack-reused 282
Empfange Objekte: 100% (338/338), 65.46 KiB | 713.00 KiB/s, Fertig.
Löse Unterschiede auf: 100% (194/194), Fertig.
[idnovic@id-lappy /tmp/tester]127$ ls
 extract_strings.sh   i18n   README.md  'usbguard applet.desktop'
 generate_mo.sh       mo     src         usbguard.desktop
[idnovic@id-lappy /tmp/tester]0$ 
```

The user may run this command with the standard working directory of /home/USERNAME/

**Comment by 6E006B** [comment]
You are correct.
I removed the . in the commit above.
Thanks && Cheers
