### ISSUE TITLE
Not working with usbguard 0.7.5

### ISSUE THREAD

**Issue by BlackDex** [k00n/usbguard-gnome#16]
This script is not working with the latest usbguard any more.
I created a PR #15 which fixes this.
But, it is not very clean, since it will not work with 0.7.4 and below.
And i probably missed some items.

**Comment by BlackDex** [comment]
I created a new PR #17, please check if this is ok :).

**Comment by 6E006B** [comment]
merged and thanks again for the contribution :)

**Comment by BlackDex** [comment]
No problem :).
