### ISSUE TITLE
Directory /opt/usbguard/ does not exist

### ISSUE THREAD

**Issue by MatejKovacic** [k00n/usbguard-gnome#20]
I have manually compiled this software on Ubuntu 20.04, but apple was not working...

So I went to `cat "/opt/usbguard-gnome/usbguard applet.desktop"` and found out this:
...
Comment=
Exec=python /opt/usbguard/src/usbguard_gnome_applet.pyc
Icon=usbguard-icon
...
Now, the problem is, that directory /opt/usbguard/ does not exists, however, /opt/usbguard-gnome/ does exists.

If I correct the /opt/usbguard-gnome/usbguard applet.desktop it is still not working, but I am able to run applet by:
`python /opt/usbguard-gnome/src/usbguard_gnome_applet.pyc`

And another question, is USBGuard Applet already part of a Gnome? Because in Ubuntu 20.04 it was not a part of it...

**Comment by muelli** [comment]
> And another question, is USBGuard Applet already part of a Gnome? Because in Ubuntu 20.04 it was not a part of it...

no.
There's another integration, though.

**Comment by 6E006B** [comment]
Thanks for the info
Fixed the paths in 8fa27d8541d431194c43215e86bff7b51d622dde
